Replace matchit.vim with fork
The repo at vim-scripts/matchit.zip has bad commit metadata:

    error: object ced6c409c9beeb0b4142d21906606bd194411d1d: badTimezone: invalid author/committer line - bad time zone

This switches to a fork of it that has fixed the git history so that git
installations with fsck enabled are able to clone it.

Co-authored-by: Brian Cunnie <bcunnie@pivotal.io>